NREL-Sienna/PowerSimulations.jl

- Manifest.toml
- README.md
closes #138 
The updates in ParameterJuMP#master are causing breaking changes. I have pinned the compatible version and made it explicit in the README.
> Addresses breaking changes in ParameterJuMP v0.1.0

- src/devices/device_models/common/duration_constraints.jl
- src/devices/device_models/thermal_generation.jl
We need to round up minimum up/down time requirement to integers.
Would prefer to have this added in PowerSystems parsing checks, rather than in constraint creation
Fixes #124
> Fix Min-up/down time constraints in UC formulation

- src/core/build_simulations.jl
- src/routines/write_model.jl
- src/simulation_models/stage_update.jl
- Fixes the Issue when Solver doesn't support SolveTime() and adds NaN to the Optimizer_log feather file instead of a Nothing
> Fix Optimizer log printing

- src/PowerSimulations.jl
- src/core/definitions.jl
[MathOptFormat](https://github.com/odow/MathOptFormat.jl) is now deprecated and the functionality is included in MOI. This PR updates PSI. 
This PR includes an update to the TOML files
> change MOF for FileFormats

- src/devices_models/device_model.jl
- src/devices_models/devices/AC_branches.jl
- src/devices_models/devices/common/add_parameters.jl
- src/devices_models/devices/common/add_variable.jl
- src/devices_models/devices/common/constraints_structs.jl
- src/devices_models/devices/common/range_constraint.jl
- src/devices_models/devices/common/timeseries_constraint.jl
- src/devices_models/devices/electric_loads.jl
- src/devices_models/devices/hydro_generation.jl
- src/devices_models/devices/renewable_generation.jl
- src/devices_models/devices/storage.jl
- src/devices_models/devices/thermal_generation.jl
- src/services_models/reserves.jl
This PR is a draft to simplify code in [timeseries_constraint.jl](https://github.com/NREL/PowerSimulations.jl/blob/dev0-2/src/devices_models/devices/common/timeseries_constraint.jl). It implements a new container `DeviceTimeSeries` and collapses the construction of time series data and constraint data into a single loop.
TODO:
- propagate changes to electric_loads.jl
> Device timeseries

- src/routines/solve_routines.jl
We were unable to simulateously redirect the output to a log file and
to the console in real time.
> Disable redirecting solver output

- .travis.yml
This line cause this backgrounded process to `sleep` for 9 minutes, and then print "still running" along with the seconds since it started running.
```
while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
```
Anything run after it need not output anything to the console. Once done, `kill %1` will kill the last background process. 
We need to do the above because on Travis any job that hasn't printed anything to the screen in 10 minutes will time out (Any job that is running for more than 50 minutes will be timed out regardless of whether it is printing anything to the screen or not).
> Prevent Travis-CI from timing out

- src/PowerSimulations.jl
- src/core/definitions.jl
- src/devices_models/device_constructors/hydrogeneration_constructor.jl
- src/devices_models/devices/hydro_generation.jl
- src/devices_models/devices/thermal_generation.jl
- src/routines/make_initial_conditions.jl
- test/test_device_hydro_generation_constructors.jl
- test/test_utils/get_test_data.jl
- test/test_utils/operations_problem_templates.jl
- Adding new formulation for `HydroDispatch` which can track energy stored in reservoir, account for inflow and spillage.
- Changed `HydroDispatchSeasonalFlow` - > `HydroDispatchReservoirFlow`
- The new formulation is called `HydroDispatchReservoirStorage` (can be named something else), the need for this emerges if we apply energy balance constraint to reservoir storage then the energy limit constraint shouldn't be applied.
- Added capability to model HydroFixed as HydroROR
> Updating Hydro Formulations

- src/PowerSimulations.jl
- src/core/cache.jl
- src/core/initial_conditions.jl
- src/core/psi_container.jl
- src/core/simulation.jl
- src/core/simulation_stages.jl
- src/devices_models/devices/hydro_generation.jl
- src/devices_models/devices/storage.jl
- test/runtests.jl
- test/test_simulation_solution.jl
- test/test_utils/get_test_data.jl
- test/test_utils/operations_problem_templates.jl
This PR sets up warms starting a stage with its previous solution. Currently is done by default if the solver allows it. When we implement kwargs into stage definitions we can make them optional. 
closes #208
> add warm start

- src/devices_models/devices/hydro_generation.jl
- The energy limit constraint for hydro where the energy limit parameter doesn't have a time index, but only device names. 
- Current method expects when there is 1 dimensional parameter to be time,so I just added made the parameter to have 2 index sets (Device, Time)
> PSIMA-116: Fixing bug in Hydro print error

- src/core/simulation.jl
- test/test_simulation_build.jl
That to make few changes to the existing methods
- Changed `get_stage_cache_definition`  to return an empty cache vector instead of nothing. (It is easier to populate empty array than a nothing)
- Added `_add_initial_condition_caches` that loops over the initial condition keys and checks if a cache is passed by the use, if not creates it.
- Changed `test_simulation_build` test to check for cache instead of error thrown
> PSIMA-145:Automating cache creation using initial conditions

- test/Project.toml
- test/runtests.jl
There are several ambiguities in the code right now. I added the Package Aqua to detect them. This is the current output 
```
6 ambiguities found
Ambiguity #1
branch_rate_constraints!(psi_container::PowerSimulations.PSIContainer, devices::InfrastructureSystems.FlattenIteratorWrapper{B}, model::PowerSimulations.DeviceModel{B,#s512} where #s512<:PowerSimulations.AbstractDCLineFormulation, system_formulation::Type{#s511} where #s511<:PowerModels.AbstractDCPModel, feedforward::Union{Nothing, PowerSimulations.AbstractAffectFeedForward}) where B<:PowerSystems.DCBranch in PowerSimulations at /Users/jdlara/.julia/packages/PowerSimulations/tDRLp/src/devices_models/devices/DC_branches.jl:67
branch_rate_constraints!(psi_container::PowerSimulations.PSIContainer, …
```
> add aqua tests

- src/devices_models/devices/storage.jl
It seems that energy_balance() expects that the order in the var_name argument is (varin, varout, varenergy). Here it was called with (varout, varin, varenergy). If the efficiency data is not all 100% this results in a wrong constraint. 
For example considering efficiency (in = 0.9, out = 0.8) the current constraint will look like:  
E__GenericBattery_{313_HEAD_STORAGE, 3} - E__GenericBattery_{313_HEAD_STORAGE, 2} - 0.9 Pout__GenericBattery_{313_HEAD_STORAGE, 3} + 1.25 Pin__GenericBattery_{313_HEAD_STORAGE, 3} = 0.0
The 1.25 times addition of the charging power to the energy is faulty.
> Incorrect order of arguments

- src/core/feedforward.jl
- src/core/simulation_sequence.jl
- src/printing.jl
- test/test_utils/operations_problem_templates.jl
Is there any reason for the occurrences of `Int64` in the code? Having them as `Int` would be good. We have a small test running which is failing for 32-bit runners and this might be the issue.
> Change instances of Int64 to Int

- src/devices_models/devices/hydro_generation.jl
The following change follows the same logic of FixedOutput for Renewables.
However, this idea is not correct. Basically, we are using the same forecast for active power for reactive power.
The solution here is essentially make Q = 0 all times, or use a constant power factor, that depending on P, will update Q. Any ideas here on how to move forward?
> Updates for FixedOutput model

- src/services_models/GroupReserve.jl
- test/test_services_constructor.jl
Fixes TimeSeries handling for `GroupReserve`. The requirement in a `GroupReserve` is supposed to be an extra constraint and shouldn't be affected by the requirements of the contributing services.
EX: `GroupReserve` is composed of Regulation and Spinning.
The market operator sets the requirement for Regulation to be 100 MWh (contributing generators should reserve together this amount, let's call their summed contribution R_reg) and Spinning to be 50 MWh (let's call their summed contribution R_spin). For security, the operator creates a new requirement of 200 MW (a `GroupReserve`) for the sum of Regulation and Spinning reserves. The constraints should be:
1) R_reg >= 100
2) R_spin >= 50
3) R_reg + R_spin >= 200
> Fix TimeSeries for GroupReserve

- src/PowerSimulations.jl
- src/core/hdf_simulation_store.jl
- src/core/param_result_cache.jl
- src/core/simulation_results.jl
- src/printing.jl
- test/test_simulation_results.jl
This PR does the following:
- Removes some built-in validation of timestamps in the store. I am confident that the code is correct without them.
- Refactors the interface between SimulationResults and SimulationStore.
- Splits StageResults from SimulationResults.
- Uses `Base.empty!` instead of `clear_simulation_results!`. I think this makes more sense, especially with `length` and `isempty`. If you disagree, I'll change it back.
Something else that crossed my mind while making these changes. `SimulationStoreParams` and `SimulationStoreStageParams` are now passed through several layers of the codebase. I suggest that we consider building these into the base Simulation or SimulationSequence structs. They really have nothing to do with the store.
> Refactor store

- src/core/operations_problem.jl
- test/test_operations_solve.jl
The serialized system was going into the current directory instead of the user-requested directory.
> Fix serialization of op problem

- src/core/psi_container.jl
This will prevent that in the future values close to 0 from using undef get confused from actual 0 values.
> fill empty param array with NaN

- src/core/service_models.jl
- src/core/simulation.jl
- src/devices_models/device_constructors/branch_constructor.jl
- src/devices_models/device_constructors/hydrogeneration_constructor.jl
- src/devices_models/device_constructors/load_constructor.jl
- src/devices_models/device_constructors/regulationdevice_constructor.jl
- src/devices_models/device_constructors/renewablegeneration_constructor.jl
- src/devices_models/device_constructors/storage_constructor.jl
- src/devices_models/device_constructors/thermalgeneration_constructor.jl
- src/devices_models/devices/AC_branches.jl
- src/devices_models/devices/DC_branches.jl
- src/devices_models/devices/common/add_variable.jl
- src/devices_models/devices/common/cost_functions.jl
- src/devices_models/devices/electric_loads.jl
- src/devices_models/devices/hydro_generation.jl
- src/devices_models/devices/interfaces.jl
- src/devices_models/devices/regulation_device.jl
- src/devices_models/devices/renewable_generation.jl
- src/devices_models/devices/storage.jl
- src/devices_models/devices/thermal_generation.jl
- src/network_models/powermodels_interface.jl
- src/services_models/agc.jl
- src/services_models/reserves.jl
- src/services_models/services_constructor.jl
- test/test_device_thermal_generation_constructors.jl
@kdheepak This PR fixes an incorrect implementation of the use of warm start across the package. Due to the use of defaults, it was working but the implementation was incoherent. Some constructors would take settings others would take formulations. 
This situation leads to multiple confusions on the behavior of the package and made it hard to debug. I added types to all the functions to avoid future incorrect behaviors. 
One note about implementation, I implemented the formulations as instances just because it seemed to be your preference, makes the code review easier, and follows better the way things are currently implemented. @daniel-thom any thoughts on the use of instances vs types in the fix for the problem? 
Given the urgency to address these issues, I will keep the PR open for 24 …
> fix incorrect implementations

- src/PowerSimulations.jl
- src/core/definitions.jl
- src/core/simulation.jl
- src/core/simulation_results.jl
- test/test_simulation_results.jl
This allows blocking of reading results if the simulation failed.
Fixes #629
> Serialize simulation status

- src/PowerSimulations.jl
- src/core/definitions.jl
- src/core/simulation.jl
- src/core/simulation_results.jl
- test/test_simulation_results.jl
1. Serialize the status of a simulation so that if a user tries to load results for a failed simulation, it will fail by default.
2. Do not load systems by default in SimulationResults. Deserialize on the first access by the user or let the user set them manually.
> Improve loading of simulation results

- src/core/problem_results.jl
- test/test_simulation_results.jl
this PR addresses a bug where `get_realized_results` fails when `ProblemResults` is created without a `System`.
> fixing realized results retreval without system

- src/core/constraints.jl
- src/core/optimization_container.jl
- src/devices_models/device_constructors/branch_constructor.jl
- src/devices_models/devices/AC_branches.jl
- src/devices_models/devices/DC_branches.jl
- src/devices_models/devices/hydro_generation.jl
- src/network_models/powermodels_interface.jl
- test/test_device_branch_constructors.jl
- test/test_network_constructors.jl
- test/test_operations_problem.jl
- test/test_utils/model_checks.jl
This PR addresses a bug where the :network_flow constraint container was being created for every branch device type, overwriting previous instances of the container.
> resolving bug in PTDF with lines and transformers

- src/core/operations_problem.jl
- src/core/param_result_cache.jl
- src/core/settings.jl
- src/core/simulation.jl
- test/test_simulation_results.jl
This PR improves performance when time series data is read during a simulation.
The current implementation repeatedly reads in very small increments. Suppose a simulation has many components with Deterministic forecasts with a horizon of 24. It will read 24 floats for every component at every execution. 24 x 8 = 192 bytes. This is very inefficient for the OS and storage system. When reading sequentially, which is what we do here, it is much better to read in large chunks.
This PR uses a feature in InfrastructureSystems to prefetch 1 MiB of chronological time series data for each time array into cache at a time and then service the small reads from that cache.
Here is before & after data from a simulation with a System that has 1350 Deterministic forecasts across components. This shows …
> Prefetch sequential reads of time series data

- src/core/optimization_container.jl
- src/devices_models/devices/AC_branches.jl
This makes some minor improvements in the speed of Standard PTDF. However, there are some underlying challenges still with ParameterJuMP https://github.com/JuliaStochOpt/ParameterJuMP.jl/issues/85
> performance patch3

- src/core/constraints.jl
- src/devices_models/devices/AC_branches.jl
- src/devices_models/devices/common/device_range_constraints.jl
- src/devices_models/devices/common/range_constraint.jl
- src/devices_models/devices/common/reactivepower_constraints.jl
- src/devices_models/devices/electric_loads.jl
- src/devices_models/devices/hydro_generation.jl
- src/devices_models/devices/regulation_device.jl
- src/devices_models/devices/renewable_generation.jl
- src/devices_models/devices/storage.jl
- src/devices_models/devices/thermal_generation.jl
- test/test_device_thermal_generation_constructors.jl
- test/test_jump_model_utils.jl
- test/test_services_constructor.jl
- Refactor RangeConstraint
- Use dispatch instead of struct fields for Range Constraints
- Refactor Range Constraint for ThermalGen
- Fix incorrect dispatch
- Generalize code for ActivePowerVariableLimitsConstraint and ReactivePowerVariableLimitsConstraint
- Fix tests
- Update test comments
- Change binary_variables name
- Add old code
- Update test_jump_model_utils.jl
- Hydro constraints
- Add TODO for DispatchRunOfRiver
- Fix more Hydro tests
- Remove commented code
- Fix tests for hydro
- Fix more Storage tests
- Fix more tests
- Update tests for storage
- Reorganize content
- Refactor to simplify code (broken tests)
- Fix thermal constraints in refactor
- Fix hydro tests and remove spec code
- Fix storage tests and remove spec code
> Refactor range constraints

- src/devices_models/device_constructors/common/constructor_validations.jl
This is dependent on https://github.com/NREL-SIIP/PowerSystems.jl/pull/811 and so CI will fail until there is a new PSY tag.
> Check for invalid components at build time

- src/PowerSimulations.jl
- src/core/optimization_container.jl
- src/operation/decision_model.jl
- src/operation/emulation_model.jl
- src/operation/operation_model_interface.jl
- src/operation/operation_model_serialization.jl
- src/operation/problem_results.jl
- src/simulation/simulation_problem_results.jl
- src/utils/dataframes_utils.jl
- src/utils/powersystems_utils.jl
- test/test_model_decision.jl
- test/test_model_emulation.jl
1. DecisionModel and EmulationModel can be deserialized and re-run as long as the optimizer and JuMP model are provided.
2. ProblemResults can be constructed from either DecisionModel or EmulationModel.
3. ProblemResults can be serialized in binary form. The PSY.System can be restored upon deserialization if the file is stored in the same location as the serialized model.
4. Change the solve!/run! functions to support automatic build, results serialization, and results export.
5. Consolidated some common functions between DecisionModel and EmulationModel.
> Refactor OperationProblem results handling

- src/simulation/simulation.jl
- test/test_simulation_execute.jl
The test are failing because of the hybrid simulation test which  is caused by the incompatibility between sparse axis arrays and  the simulation state code.
> Fixing System state updates

- src/operation/problem_results.jl
This leaves only one set of plural read_X methods. Those methods do not accept kwargs.
> Remove read_variables from ProblemResults

- src/simulation/simulation_internal.jl
- src/simulation/simulation_results.jl
- test/test_simulation_partitions.jl
- test/test_simulation_results.jl
#874 caused a regression in handling of simulation output directories when a single simulation is run multiple times. This fixes that issue.
> Fix handling of simulation execution directory

- docs/src/formulation_library/Branch.md
- src/PowerSimulations.jl
- src/core/constraints.jl
- src/core/formulations.jl
- src/core/optimization_container.jl
- src/core/variables.jl
- src/devices_models/device_constructors/branch_constructor.jl
- src/devices_models/devices/AC_branches.jl
- src/devices_models/devices/DC_branches.jl
- src/devices_models/devices/common/add_to_expression.jl
- src/network_models/pm_translator.jl
- src/operation/operation_problem_templates.jl
- test/test_device_branch_constructors.jl
- test/test_utils/operations_problem_templates.jl
Fixes issue with the incorrect specification of HVDC flow limits. It also renames the existing formulation to P2P. 
Currently, the HVDCDispatch Formulation seems to be implemented incorrectly, given that it isn't really meant to handle bi-directional HVDC with losses.  
I have corroborated that DCPPowerModel and StandardPTDF match the results of the line flows in the system. 
closes #897
> fix p2p hvdc

- docs/src/formulation_library/Branch.md
- src/PowerSimulations.jl
- src/core/constraints.jl
- src/core/formulations.jl
- src/core/optimization_container.jl
- src/core/variables.jl
- src/devices_models/device_constructors/branch_constructor.jl
- src/devices_models/devices/AC_branches.jl
- src/devices_models/devices/DC_branches.jl
- src/devices_models/devices/common/add_to_expression.jl
- src/devices_models/devices/common/range_constraint.jl
- src/devices_models/devices/thermal_generation.jl
- src/network_models/pm_translator.jl
- src/operation/operation_problem_templates.jl
- src/utils/generate_valid_formulations.jl
- src/utils/powersystems_utils.jl
- test/test_device_branch_constructors.jl
- test/test_network_constructors.jl
- test/test_utils/model_checks.jl
- test/test_utils/operations_problem_templates.jl
closes #894 
This PR adds a formulation compatible with StandardPTDF and DCPPowerFlow for the phase control in phase shifters. Note that there is no need to implement PDF matrices here.
> ps power control

- src/utils/jump_utils.jl
When a generator uses quadratic heat rates, the corresponding row is undefined in the constraint `DenseAxisArray` under `PSI.ConstraintKey{PSI.PieceWiseLinearCostConstraint, PSY.ThermalStandard}("")`.
This causes an error when compute_conflict! is called
```
┌ Error: Can't compute conflict
│   exception =
│    UndefRefError: access to undefined reference
│    Stacktrace:
│      [1] getindex
│        @ ./array.jl:925 [inlined]│      [2] getindex
│        @ ~/.julia/packages/JuMP/Xw2ck/src/Containers/DenseAxisArray.jl:348 [inlined]
│      [3] check_conflict_status(jump_model::JuMP.Model, constraint_container::JuMP.Containers.DenseAxisArray{JuMP.ConstraintRef, 2, Tuple{Vector{String}, UnitRange{Int6$
}}, Tuple{JuMP.Containers._AxisLookup{Dict{String, Int64}}, …
```
> Fix check_conflict_status on undefined constraints

- src/devices_models/devices/hydro_generation.jl
As Jarred had reported some issue with the Reservoir Budget formulation which initial was built for HydroEnergyReservoir, this should make sure it works for HydroDispatch and uses the correct multiplier.
> adding a minor bug fix for hydro multiplier

- src/devices_models/device_constructors/renewablegeneration_constructor.jl
- src/devices_models/devices/renewable_generation.jl
Note that if a renewable unit has only reg-up services, it will add the constraint for reserve down: `P_out >= 0.0`, that is redundant with the lower bound.
> Add reserves down for renewable dispatch

- src/PowerSimulations.jl
- src/core/dataset.jl
- src/core/dataset_container.jl
- src/core/optimization_container.jl
- src/core/results_by_time.jl
- src/core/store_common.jl
- src/operation/abstract_model_store.jl
- src/operation/decision_model.jl
- src/operation/decision_model_store.jl
- src/operation/emulation_model.jl
- src/operation/emulation_model_store.jl
- src/operation/operation_model_interface.jl
- src/operation/problem_results.jl
- src/parameters/update_parameters.jl
- src/simulation/decision_model_simulation_results.jl
- src/simulation/emulation_model_simulation_results.jl
- src/simulation/hdf_simulation_store.jl
- src/simulation/in_memory_simulation_store.jl
- src/simulation/realized_meta.jl
- src/simulation/simulation.jl
- src/simulation/simulation_problem_results.jl
- src/simulation/simulation_results.jl
- src/simulation/simulation_state.jl
- src/utils/dataframes_utils.jl
- src/utils/jump_utils.jl
- test/test_simulation_build.jl
- test/test_simulation_results.jl
- test/test_simulation_store.jl
- test/test_utils.jl
This PR refactors the storage and access of results in order to improve performance. DataFrames are replaced by DenseAxisArrays. It also optimizes the generation of realized results.
Removed a lot of duplication in these methods and underlying code. Callers should now use `read_results_with_keys` instead.
```
read_aux_variables_with_keys
read_duals_with_keys
read_expressions_with_keys
read_parameters_with_keys
read_variables_with_keys
```
> Speedup reading of results

- src/core/network_model.jl
The code was updated by removing the error thrown in case of presence of two reference buses.
Tests were executed and the different methods passed, except for two. 
NOTE: the following models were not successful for the following reasons.
- SOCWRConicPowerModel -> unable to find a proper solver to test
- DCPLLPowerModel -> tests on sub-system balance fail
> 2 reference bus systems.

- src/devices_models/device_constructors/branch_constructor.jl
- src/devices_models/device_constructors/constructor_validations.jl
- src/devices_models/device_constructors/hvdcsystems_constructor.jl
- src/devices_models/device_constructors/load_constructor.jl
- src/devices_models/device_constructors/regulationdevice_constructor.jl
- src/devices_models/device_constructors/renewablegeneration_constructor.jl
- src/devices_models/device_constructors/thermalgeneration_constructor.jl
This PR allows SnoopCompile.jl to generate precompile statements for PowerSimulations.jl. In many cases I removed unused parameterized type variables. In other cases they were being used and I replaced uses with `typeof(x)`. There should not be any functional or performance difference.
If this change is approved, I can move forward with integrating SnoopCompile.jl with this package in a separate branch. The only other realistic alternative is to report an issue with SnoopCompile.jl and see if they can help.
> Replace parameterized type variables

- src/simulation/optimization_output_cache.jl
Check this discussion for the issue of cat: https://github.com/JuliaLang/julia/issues/30796
> Replace cat with preallocated array to fix stackoverflow issue

- src/core/device_model.jl
- src/core/service_model.jl
> fix uses of default attributes

- src/services_models/services_constructor.jl
This method was called in an incorrect spot. Not having a test make it go through
> remove incorrect method call

- src/devices_models/devices/thermal_generation.jl
> MultiStart with nothing 

- src/PowerSimulations.jl
- src/core/formulations.jl
- src/core/optimization_container.jl
- src/devices_models/device_constructors/branch_constructor.jl
- src/devices_models/devices/HVDCsystems.jl
- src/devices_models/devices/common/add_to_expression.jl
- src/network_models/copperplate_model.jl
- src/network_models/network_constructor.jl
- src/network_models/pm_translator.jl
- src/network_models/powermodels_interface.jl
- test/test_network_constructors.jl
> remove changes related to PTDFNetwork

- src/utils/jump_utils.jl
You need to use the setting `detailed_stats` to get it.
> add mipgap to caputred stats

- docs/src/formulation_library/General.md
- docs/src/formulation_library/Load.md
- docs/src/formulation_library/RenewableGen.md
- src/devices_models/devices/common/objective_functions.jl
- src/devices_models/devices/thermal_generation.jl
- src/operation/decision_model.jl
- src/operation/emulation_model.jl
- src/parameters/update_parameters.jl
- src/utils/powersystems_utils.jl
The second part of a significant refactor of Sienna cost data structures (part 1 is [here](https://github.com/NREL-Sienna/PowerSystems.jl/pull/1056#issuecomment-1959057500)). The main focus here is to bring PowerSimulations.jl up to date with the elimination of `VariableCost` in favor of `FunctionData`. That entails these changes in PowerSimulations:
- Rewrite some documentation to refer to the new cost structs
- Replace all instances of `VariableCost`, and some instances of contents of `VariableCost`, with `FunctionData`
On the latter point, I am not completely sure if I made the switch from using `FunctionData` to using raw data (vectors of tuples) at the proper place; I'd appreciate review of that.
Tests pass:
> Variable Cost Refactor Part 2: PowerSimulations

- src/operation/decision_model.jl
- src/operation/emulation_model.jl
- src/simulation/hdf_simulation_store.jl
- src/simulation/in_memory_simulation_store.jl
- src/simulation/simulation.jl
- src/simulation/simulation_problem_results.jl
- test/test_simulation_results.jl
Objective: The simulations postprocessing code in PowerAnalytics.jl needs to have access to the systems used by the simulations. Those systems are not serialized if the user opts out of that feature. Ensure that these are always available.
This is the PowerSimulations portion of the solution. I added comparable branches in PowerSystems.jl and InfrastructureSystems.jl. Let me know if the interfaces here meet your needs and then I’ll open sibling PRs.
> Serialize System components to HDF5

- README.md
- src/simulation/decision_model_simulation_results.jl
- src/simulation/emulation_model_simulation_results.jl
- src/simulation/realized_meta.jl
- src/simulation/simulation_problem_results.jl
- test/test_simulation_results.jl
This fixes #1070 and #1072.
There is some inherent overhead to creating large arrays that cannot be avoided, but now that we use the cache the time for repeated calls to `_read_results(Matrix{Float64}...` on my big dataset has decreased 30x from 0.09s to 0.003s:
```julia
julia> @time results_mat = PSI._read_results(Matrix{Float64}, res, variables, timestamps, nothing)
0.003551 seconds (340 allocations: 7.419 MiB)
```
This is much better and closes the issue but is still unnecessarily heavy-handed for my PowerAnalytics component-wise reads, so later I may seek to add an option to PowerSimulations to perform `read_results_with_keys` for only one component at a time.
Ended up being more refactoring than initially planned, but the upshot is that for the `DecisionModelSimulationResults` method …
> Fix caching behaviors: #1070, #1072, #1074

- src/operation/decision_model.jl
- src/simulation/simulation_problem_results.jl
- src/simulation/simulation_results.jl
- test/runtests.jl
- test/test_simulation_results.jl
> Expand get_decision_problem_results with kwargs

- src/simulation/decision_model_simulation_results.jl
- src/simulation/emulation_model_simulation_results.jl
- src/simulation/simulation_problem_results.jl
This PR attempts to address the concerns in #1018. I don’t think that issue is valid. There is no way to have a consistent interface with the in-memory store and the HDF5 store. The HDF5 store must be opened with a file path:
```
open_store(HdfSimulationStore, simulation_store_path, "r") do store
end
```
The in-memory store is already open. What would it look like?
```
open(InMemorySimulationStore, _, “r”, store) do store
end
```
It’s a different interface no matter how you do it.
There is a concern underlying the issue above that we have a code block that makes a non-straightforward inference about the type of the store. This addresses that.
There was another concern at https://github.com/NREL-Sienna/PowerSimulations.jl/pull/1073/files#r1512052861 which says that we should not have …
> Refactor store selection process

- src/simulation/decision_model_simulation_results.jl
- test/test_simulation_results.jl
Two main things here:
1. `load_results!` was opening a store even if all the requested results were already cached; opening the store is now left to `_read_results` after it decides whether it needs to do so.
2. `read_results_with_keys` is slowish even if the results are already cached because a lot of data has to be converted to DataFrame. Now there is an optional kwarg to request a certain list of columns and only those will be converted, resulting in much (~1000x on large datasets) less memory usage and much faster call times.
The result is that `load_results!` and `read_results_with_keys` can be called thousands of times in a tight loop as PowerAnalytics iterates over components and it's not horrendously inefficient (just a few seconds total for large datasets). Leaving as draft in …
> Further results cache optimizations to support PowerAnalytics

- test/includes.jl
- test/runtests.jl
This will allow parallel testing with SiennaIntegrationTests. It will also allow people to test a single file by running
```
julia> include(“test/includes.jl”)
julia> include(“test/test_X.jl”)
```
> Enable parallel tests by moving includes to one file

- src/devices_models/device_constructors/branch_constructor.jl
- src/devices_models/devices/thermal_generation.jl
- src/simulation/hdf_simulation_store.jl
- src/simulation/simulation.jl
- test/test_device_thermal_generation_constructors.jl
Perhaps there was a mis-merge recently. I fixed the variable names in branch_constructor.jl. There was another error caused by a merge from main into psy4.
There is still a breakage in the psy4 branch.
```
┌ Error: simulation failed
│   exception =
│    MethodError: no method matching write_result!(::PowerSimulations.HdfSimulationStore, ::Symbol, ::PowerSimulations.ConstraintKey{CopperPlateBalanceConstraint, System}, ::Int64, ::DateTime, ::Matrix{Float64})
```
```
│    Stacktrace:
│      [1] write_result!(store::PowerSimulations.HdfSimulationStore, model_name::Symbol, key::PowerSimulations.ConstraintKey{CopperPlateBalanceConstraint, System}, index::Int64, simulation_time::DateTime, data::JuMP.Containers.DenseAxisArray{Float64, 1, Tuple{Vector{String}}, …
```
> Merge fixes

- src/PowerSimulations.jl
- test/test_model_decision.jl
Fixes https://github.com/NREL-Sienna/PowerSimulations.jl/issues/1125 by adding some imports. At some point we should do this more holistically; see https://github.com/NREL-Sienna/InfrastructureSystems.jl/issues/388.
> Add imports to fix bug 1125, test that

- src/devices_models/device_constructors/thermalgeneration_constructor.jl
- src/devices_models/devices/common/objective_function/piecewise_linear.jl
- src/devices_models/devices/electric_loads.jl
- src/services_models/services_constructor.jl
Closes #1100 
Closes #1103 
Closes #1134
Closes #1135
> Fix multiple issues

- src/devices_models/devices/thermal_generation.jl
> fix incorrect getter

- src/devices_models/device_constructors/branch_constructor.jl
> Fix Unbounded HVDC model for Copperplate

- src/parameters/update_container_parameter_values.jl
This code was consuming a lot of time to lookup time series UUIDs when those values are already cached.
It should address https://github.com/NREL-Sienna/InfrastructureSystems.jl/issues/409
> Use cached time series UUID

- src/devices_models/devices/common/add_to_expression.jl
- test/test_network_constructors.jl
Addresses https://github.com/NREL-Sienna/PowerSimulations.jl/issues/1208
* Add a specific method to add slacks on balance constraints for `AreaBalancePowerModel`
> extend expression for AreaBalance equations

- docs/src/api/PowerSimulations.md
- docs/src/formulation_library/ThermalGen.md
- src/PowerSimulations.jl
- src/core/variables.jl
- src/devices_models/device_constructors/thermalgeneration_constructor.jl
- src/devices_models/devices/common/add_to_expression.jl
- src/devices_models/devices/common/rateofchange_constraints.jl
- src/devices_models/devices/thermal_generation.jl
- test/test_device_thermal_generation_constructors.jl
Closes #1204 
Add slacks for UB and LB constraints for thermal units. It uses the `use_slacks` of the device model, so to enable, using:
```
thermal_device_model = DeviceModel(
ThermalStandard,
ThermalStandardUnitCommitment;
use_slacks = true,
)
set_device_model!(template_uc, thermal_device_model)
```
will enable the slacks.
The slack variables are added to the objective function with a cost of `2e5`, using the constraint violation cost.
Here is how it looks for a RampConstraint UB:
```
-ActivePowerVariable_ThermalStandard_{107_CC_1, 1} + ActivePowerVariable_ThermalStandard_{107_CC_1, 2} - 1.6999999999999997 StartVariable_ThermalStandard_{107_CC_1, 2} - PowerSimulations.ActivePowerVariableSlackUB_ThermalStandard_{107_CC_1, 2} + ActivePowerReserveVariable_VariableReserve{ReserveUp}_Spin_Up_ …
```
> Add Thermal Slacks for UB and LB constraints (including ramps)

- src/PowerSimulations.jl
- src/simulation/get_components_interface.jl
- src/simulation/simulation_problem_results.jl
- src/utils/printing.jl
- test/test_model_decision.jl
- test/test_simulation_results.jl
Companion to and dependent on
- https://github.com/NREL-Sienna/InfrastructureSystems.jl/pull/342
- https://github.com/NREL-Sienna/PowerSystems.jl/pull/1197
. The main thing here is we want `get_components` to work on `IS.Results` such that `get_components` on a `Results` is like `get_available_components` on its attached `System` (or attached `IS.SystemData`, etc.). The implementation of this behavior is in the IS PR, but following the design set out [here](https://github.com/NREL-Sienna/PowerSystems.jl/blob/037435f4d7c0198c52e0fa29af0d05f7ee364bc7/src/get_components_interface.jl#L1), we need to define `PSY.get_components` aliases that redirect to the appropriate `IS.get_components` methods to keep the documentation user-friendly. That cannot be done in IS and (correct me if I'm wrong) it …
> Add `ComponentSelector` feature: PSI portion

- src/devices_models/devices/common/objective_function/piecewise_linear.jl
- src/utils/powersystems_utils.jl
> update cost functions for thermal dispatch no min

- src/core/event_model.jl
- src/simulation/simulation_state.jl
Adding the `update_system_state!` for the `AvialableStatusParameter` which was previously erroring
> Implement missing function 

- src/simulation/simulation_state.jl
This is a fix we dicussed together last week, to set the entire horizon to zero after an outage.
> Set full horizon to zero

- src/parameters/update_container_parameter_values.jl
- src/simulation/simulation_state.jl
For parallel testing on larger system
> make geometric work again

- src/devices_models/devices/AC_branches.jl
- src/devices_models/devices/TwoTerminalDC_branches.jl
> Fix HVDC Lossless model bug in Copperplate network

- src/simulation/simulation_results.jl
- deleted line 214 fixing get_decision_problem docstring
> fixed get_decision_problem_docstring

- docs/src/api/PowerSimulations.md
- src/simulation/simulation_results.jl
https://github.com/NREL-Sienna/PowerSimulations.jl/pull/1240 surfaced an issue in the `get_decision_problem_results` docstring that this fixes. The other reason the docs build was failing is that the new power flow-related auxiliary variables were not included; here I add a new section and put all the auxiliary variables there.
> Fix docs build, add aux variable section

- src/simulation/decision_model_simulation_results.jl
- src/utils/printing.jl
Companion PR with: https://github.com/NREL-Sienna/InfrastructureSystems.jl/pull/438
The main change is related when having to do read_realized_terms in a Simulation and generating the ranges in DecisionProblems without having available the methods for step. 
The main problem happens now when you received a single simulation step or a single time step, and having to create a step in that case. 
The approach here is covering all the previous cases to properly have the necessary intervals and resolutions in those cases. It took some time to debug this. Tests are passing locally with the proper IS branch:
Also updated the printing as we don't have step now.
> Update to `Vector{DateTime}` in Results

- src/devices_models/devices/common/objective_function/common.jl
- src/devices_models/devices/thermal_generation.jl
- test/test_device_thermal_generation_constructors.jl
Fixes #1298
Fixes #1297
Does not handle the time varying case or non-thermal devices (e.g., does not fix #1299). Adds tests sufficient to fail in the absence of these fixes, but I still think we could use more rigorous testing of this kind of thing in general.
> Fix #1298, fix #1297 for thermals, test that

- src/core/network_model.jl
- src/core/optimization_container.jl
- src/devices_models/devices/AC_branches.jl
- src/devices_models/devices/common/add_to_expression.jl
- src/initial_conditions/initialization.jl
- src/network_models/network_slack_variables.jl
- src/network_models/pm_translator.jl
- src/network_models/powermodels_interface.jl
Makes compatible with the `psy5` branch in `PowerNetworkMatrices.jl` by changing radial reduction to network reduction. 
There are still a few tests with failures:
`Line and Monitored Line models with slacks`
`MarketBidCost with time series startup and shutdown, ThermalStandard `
`Test simulation partitions`
> change names for pnm compatibility

- src/core/optimization_container.jl
- src/devices_models/device_constructors/branch_constructor.jl
- src/devices_models/devices/common/add_to_expression.jl
- src/devices_models/devices/common/objective_function/market_bid.jl
- src/devices_models/devices/common/objective_function/piecewise_linear.jl
- src/services_models/agc.jl
- src/services_models/reserve_group.jl
- src/services_models/services_constructor.jl
- src/simulation/simulation.jl
Still needs testing but this should address the issue with the area/synch regions mismatch @llavin13 reported in #1269. 
One situation to note here is that we need to throw meaningful errors when users add TransmissionInterfaces to AreaBalance models because it doesn't make sense since there aren't any line flows calculated.
> hvdc area fix
