NREL-Sienna/PowerSimulations.jl

test/load_constructors.jl
test/network_constructors.jl
test/renewable_generation_constructors.jl
test/storage_constructors_test.jl
test/thermal_generation_constructors.jl
test/variables.jl

- Added test to check number of variables/constraints added to JuMP model 
- Doesn't match PowerSystems format for test

Test JuMP model 

---

src/PowerSimulations.jl
src/core/core_structs/canonical_model.jl
src/core/operations_constructor.jl
src/devices/device_models/common/cost_functions.jl
src/devices/device_models/common/undef_check.jl
src/devices/device_models/electric_loads/injection_expression.jl

Also fixed a few bugs not caught by the tests.
Note the changes in src/devices/device_models/electric_loads/injection_expression.jl.  Looking at the PowerSystems.jl code, the type PowerLoad is a subtype of ElectricLoad.  I think what I did is correct but someone should definitely make sure.

Changes to enable StructJuMP model construction.

---

src/devices/device_models/common/cost_functions.jl

This Pull Request will tackle the following issues

Fixing PWL Cost implementation

---

src/routines/get_results.jl

remove the rounding of results in the DataFrame
closes #164

remove rounding of results

---

src/devices/device_models/common/cost_functions.jl

Bug fixed in pwl check function

---

src/devices/device_models/common/cost_functions.jl
src/devices/device_models/common/duration_constraints.jl
src/devices/device_models/common/make_initial_conditions.jl

- Retrospective Constraint supports both Parameter or Float initial conditions 
- Mixed and look-ahead Minor fix in inequality sign

Duration Constraints Fixes

---

src/core/build_operations.jl
src/network_models/network_constructor.jl
test/runtests.jl
test/test_network_constructors.jl
test/test_operation_model_constructor.jl
test/test_operation_model_solve.jl
test/test_utils/model_checks.jl

this addresses the network tests in #189

Fix net tests

---

src/devices/device_models/common/duration_constraints.jl
src/routines/get_results.jl
test/test_hydro_generation_constructors.jl
test/test_storage_constructors.jl

Test Updates

---

.appveyor.yml
.travis.yml
Manifest.toml
src/PowerSimulations.jl
src/core/build_cache.jl
src/core/build_simulations.jl
src/core/core_structs/aux_structs.jl
src/core/core_structs/cache_models.jl
src/core/core_structs/canonical_model.jl
src/core/core_structs/chronology.jl
src/core/core_structs/device_model.jl
src/core/core_structs/feedforward_model.jl
src/core/core_structs/initial_conditions.jl
src/core/core_structs/operation_model.jl
src/core/core_structs/simulation_model.jl
src/core/core_structs/simulations_stages.jl
src/devices/device_models/common/cost_functions.jl
src/devices/device_models/common/range_constraint.jl
src/devices/device_models/storage.jl
src/devices/device_models/thermal_generation.jl
src/routines/make_initial_conditions.jl
src/simulation_models/feedforward_models.jl
src/simulation_models/stage_update.jl
src/utils/printing.jl
test/test_base_structs.jl

The model will check if linear PWL function can be implemented, if not it will use SOS-2 
closes #173

SOS2 Cost implementation 

---

src/utils/printing.jl

printing Operation Model model reference instead of "Operation Model" in a more organized manner.

printing capability

---

src/core/build_operations.jl
src/core/build_simulations.jl
src/devices/device_constructors/thermalgeneration_constructor.jl
src/routines/get_results.jl
src/utils/plot_results.jl
src/utils/printing.jl

Minor changes from the suggestions are here. I am going at it in pieces.

address small changes suggested by kd

---

src/routines/get_results.jl

@Lilyhanig This PR might break some of the results grabbing. It is basically adding the capability to write 1-dimensional data frames and 3 dimensional data frames

add other dimension cases for get_results

---

src/routines/get_results.jl
src/routines/solve_routines.jl
src/routines/write_model.jl

this sets the correct timestamp for the simulation results

fixing time stamp isue

---

src/devices_models/device_constructors/hydrogeneration_constructor.jl
src/devices_models/devices/hydro_generation.jl
src/routines/make_initial_conditions.jl
test/runtests.jl
test/test_hydro_generation_constructors.jl
test/test_utils/get_test_data.jl

Adds support for HydroFixed and HydroDispatch formulations in PowerSimulations
(Fresh PR)

Updating Hydro models

---

src/devices_models/device_constructors/branch_constructor.jl
src/devices_models/device_constructors/hydrogeneration_constructor.jl
src/devices_models/device_constructors/load_constructor.jl
src/devices_models/device_constructors/renewablegeneration_constructor.jl
src/devices_models/device_constructors/storage_constructor.jl
src/devices_models/devices/AC_branches.jl
src/devices_models/devices/DC_branches.jl
src/devices_models/devices/electric_loads.jl
src/devices_models/devices/hydro_generation.jl
src/devices_models/devices/renewable_generation.jl
src/devices_models/devices/storage.jl
src/devices_models/devices/thermal_generation.jl

also removing commented out code

adding feedforward to constraints

---

src/core/feed_forward.jl

- Adding `IntegralLimitFF` struct in FeedForward and function for building the constraints

IntegralLimit Feed Forward

---

src/routines/get_results.jl
src/routines/solve_routines.jl
src/routines/write_results.jl
src/utils/dual_results.jl
src/utils/simulation_results.jl
src/utils/simulation_results_reference.jl
test/Project.toml
test/runtests.jl
test/test_dual_constraints.jl
test/test_write_results.jl

add test for all write_results functions across operation, simulation, and simulation with dual constraints in the results.

add tests for write results

---

src/PowerSimulations.jl
src/core/feed_forward.jl
src/devices_models/devices/hydro_generation.jl
test/test_data/data_5bus_pu.jl
test/test_device_hydro_generation_constructors.jl
test/test_simulation_execute.jl
test/test_utils/get_test_data.jl
test/test_utils/operations_problem_templates.jl

- Allowing HydroDispatch constructor to create IntegralFF constraint or Energy Limit constraint depending on the FeedForward passed
This is the same PR as the previous one but clean git history

Adding IntegralLimitFF implementation for HydroDispatch

---

src/core/operations_problem.jl
src/devices_models/devices/electric_loads.jl
src/devices_models/devices/hydro_generation.jl
src/devices_models/devices/renewable_generation.jl

- minor fixes to remove default arguments to _get_time_series() methods

removing default arguments from _get_time_series methods

---

src/devices_models/device_constructors/hydrogeneration_constructor.jl
src/devices_models/devices/common/energy_balance_constraint.jl
src/devices_models/devices/hydro_generation.jl
test/test_device_hydro_generation_constructors.jl

- Updated Hydro Reservoir constraints 
- Removed support for any UC hydro formulations

Updating to Hydro Formulations 

---

src/PowerSimulations.jl
src/devices_models/device_constructors/hydrogeneration_constructor.jl
src/devices_models/devices/hydro_generation.jl
test/test_data/data_5bus_pu.jl
test/test_device_hydro_generation_constructors.jl
test/test_services_constructor.jl
test/test_simulation_solution_loading.jl
test/test_utils/get_test_data.jl
test/test_utils/operations_problem_templates.jl

Needs PowerSystems branch to be merged for this to pass.

Renaming PowerSystems Hydro Structs

---

src/PowerSimulations.jl
src/templates/operations_problem_templates.jl
test/test_operations_constructor.jl

creates functions to return `OperationsProblemTemplate`s for standard formulations for:
- Unit Commitment
- Economic Dispatch

add template functions

---

src/PowerSimulations.jl
src/devices_models/devices/common.jl

I made simple changes to the include order:
This in my opinion reads better than it was before and it also imported successfully, so no circular dependency issues were introduced by this change.

Change include order

---

src/core/feedforward.jl
src/devices_models/devices/common/energy_balance_constraint.jl
src/devices_models/devices/common/rateofchange_constraints.jl
src/devices_models/devices/common/timeseries_constraint.jl
src/network_models/powermodels_interface.jl
src/network_models/ptdf_model.jl
src/operations_problems_templates.jl
src/printing.jl
test/test_data/data_5bus_pu.jl
test/test_simulation_solution.jl
test/test_utils/operations_problem_templates.jl

fix feedforward print bug

---

src/core/simulation.jl
src/core/simulation_sequence.jl
test/test_simulation_build.jl
test/test_simulation_sequence.jl
test/test_simulation_solution.jl

- Changed cache dict definition in Simulation Sequence https://github.com/NREL/PowerSimulations.jl/blob/b8e2e70843c79f8e8bb30f2adf394740dbe0c7b9/src/core/simulation_sequence.jl#L169
-  This will allow multiple stages to modify information in cache

Fixing Cache References

---

src/PowerSimulations.jl
src/core/cache.jl
src/core/initial_conditions.jl
src/core/simulation.jl
src/core/simulation_stages.jl
src/devices_models/devices/hydro_generation.jl
src/devices_models/devices/storage.jl
test/test_simulation_solution.jl
test/test_utils/get_test_data.jl
test/test_utils/operations_problem_templates.jl

Changes :
This is Copy of PR #370

Adding Energy Storage Cache

---

test/test_simulation_execute.jl

- The RH test was looking at the 1st index in the ED simulation rather than the last index for initial condition for the next UC

Fixing Test bug 

---

src/devices_models/device_constructors/hydrogeneration_constructor.jl
src/devices_models/devices/hydro_generation.jl
test/test_device_hydro_generation_constructors.jl

- Removed unused constructors
- Added more tests

Improving coverage for Hydro constructors

---

src/PowerSimulations.jl
src/core/operations_problem_results.jl
src/core/simulation_results.jl

defines the IS.get_base_power function interface for results types in PSI. Addresses PSIMA-111

PSIMA-111 bugfix

---

src/core/cache.jl
src/core/simulation.jl
src/core/simulation_sequence.jl

- Added new field to the TimeStatusChange for establishing a units for the count 
- PSIMA-111

Fixing Cache Update

---

src/core/operations_problem.jl
src/core/simulation_results.jl
src/utils.jl

- filters empty data frames from results
- allows data frames with length < time_steps (e.g. energy parameters) to be included with results

Addresses PSIMA-126 EOFError from Feather file

---

src/core/update_initial_conditions.jl

- This PR relies on PowerSystems #453 being merged, and adding `time_at_status` field to ThermalStandard

PSIMA-132: Updating initial condition functions

---

src/devices_models/devices/common/cost_functions.jl
src/devices_models/devices/thermal_generation.jl

Needs PowerSystem#475 to be merged
Doesn't address PSIMA-167 (no-load cost is still in pwl segments)

Refactor PWL implementation

---

src/core/simulation.jl

fixing typo in storage cache creation

fixing cache typo

---

test/test_base_structs.jl
test/test_device_branch_constructors.jl
test/test_device_hydro_generation_constructors.jl
test/test_device_load_constructors.jl
test/test_device_renewable_generation_constructors.jl
test/test_device_storage_constructors.jl
test/test_device_thermal_generation_constructors.jl
test/test_network_constructors.jl
test/test_operations_constructor.jl
test/test_operations_modifications.jl
test/test_operations_solve.jl
test/test_services_constructor.jl
test/test_simulation_build.jl
test/test_simulation_execute.jl
test/test_utils/get_test_data.jl

This doesn't address all of PSIMA-147.  I'd like to take it in stages.  This removes most of the global variables and builds systems from function calls.
Note that it is likely slower than the previous version because it rebuilds systems many times.

Refactor tests to build systems in function calls

---

test/runtests.jl
test/test_base_structs.jl
test/test_device_branch_constructors.jl
test/test_device_hydro_generation_constructors.jl
test/test_device_load_constructors.jl
test/test_device_renewable_generation_constructors.jl
test/test_device_storage_constructors.jl
test/test_device_thermal_generation_constructors.jl
test/test_logging.jl
test/test_network_constructors.jl
test/test_operations_constructor.jl
test/test_operations_modifications.jl
test/test_operations_solve.jl
test/test_services_constructor.jl
test/test_simulation_build.jl
test/test_simulation_execute.jl
test/test_utils/get_test_data.jl

This PR implements infrastructure for building systems from scratch once and then rebuilding from serialized files.
It collects some stats that might be overkill for the tests; that code might be useful when we start building bigger systems.

PSIMA-147 part 2

---

src/core/simulation_results.jl
src/utils.jl
test/test_simulation_execute.jl

Fix handling of results paths with spaces

---

src/core/operations_problem_results.jl
src/core/simulation_results.jl
test/test_operations_solve.jl

fixes issue with the results getting changed in write_to_csv

---

src/core/simulation.jl
src/core/update_initial_conditions.jl
src/devices_models/device_constructors/common/constructor_validations.jl
src/devices_models/device_constructors/regulationdevice_constructor.jl
src/devices_models/device_constructors/thermalgeneration_constructor.jl
src/services_models/agc.jl
src/services_models/services_constructor.jl

Empty contributing devices case

---

src/devices_models/device_constructors/common/constructor_validations.jl
src/services_models/services_constructor.jl

addresses the comments in #494

address inconsistencies in services

---

src/PowerSimulations.jl
src/core/feedforward.jl
src/core/simulation.jl
src/devices_models/devices/common/add_parameters.jl
src/devices_models/devices/common/add_variable.jl
src/devices_models/devices/common/constraints_structs.jl
src/devices_models/devices/common/energy_balance_constraint.jl
src/devices_models/devices/common/range_constraint.jl
src/devices_models/devices/common/rateofchange_constraints.jl
src/devices_models/devices/common/timeseries_constraint.jl
src/devices_models/devices/hydro_generation.jl
src/devices_models/devices/regulation_device.jl
src/devices_models/devices/thermal_generation.jl

patch get name

---

src/services_models/reserves.jl

Fix `service_requirement_constraint` and `cost_function!` to dispatch on `AbstractReservesFormulation` following the pattern.

Fix service_requirement_constraint

---

src/core/definitions.jl
src/devices_models/device_constructors/hydrogeneration_constructor.jl
src/devices_models/device_constructors/load_constructor.jl
src/devices_models/device_constructors/renewablegeneration_constructor.jl
src/devices_models/device_constructors/thermalgeneration_constructor.jl
src/devices_models/devices/common/cost_functions.jl
src/devices_models/devices/electric_loads.jl
src/devices_models/devices/hydro_generation.jl
src/devices_models/devices/renewable_generation.jl
src/devices_models/devices/thermal_generation.jl
src/services_models/reserves.jl

This addresses long-standing issues on the cost functions. It also implements the new cost function for the joint energy - services market bid. 
It also removes some hacks to handle PWL functions cases. 
x-ref #514 
cc. @andrewrosemberg @raphaelsaavedra this is WIP for feedback. At this stage the tests don't pass but you can see the path I am taking. 
@claytonpbarrows please take a look.

refactor cost functions

---

src/services_models/reserves.jl
test/test_services_constructor.jl

Adds test for StaticReserve as RangeReserve.

Add test for StaticReserve as RangeReserve

---

Project.toml

Requires https://github.com/NREL-SIIP/PowerSystems.jl/pull/666 and https://github.com/NREL-SIIP/InfrastructureSystems.jl/pull/175 to pass.

update project toml

---

Project.toml
src/PowerSimulations.jl
src/core/operations_problem.jl
src/core/operations_problem_results.jl
src/core/simulation.jl
src/core/simulation_results.jl
src/core/simulation_stages.jl
src/network_models/ptdf_model.jl
src/utils.jl
test/Project.toml
test/runtests.jl
test/test_operations_solve.jl
test/test_simulation_execute.jl

This is a quick fix to remove the use of Feather.

remove feather

---

src/devices_models/device_constructors/branch_constructor.jl
src/devices_models/devices/AC_branches.jl
test/test_device_branch_constructors.jl
test/test_utils/model_checks.jl

adding constructor for ACBranch with unbounded Formulation

---

src/devices_models/devices/AC_branches.jl

bug fix in branch flow constraint

---

src/core/operations_problem_results.jl
src/devices_models/devices/common/constraints_structs.jl
src/devices_models/devices/common/nodal_expression.jl

This resolves an issue that I encountered where PSI was expecting a vector of floats but instead gets a vector of ints. This makes the conversion when needed.

handling time series of int values

---

src/PowerSimulations.jl
src/core/operations_problem.jl
src/core/operations_problem_results.jl
src/core/psi_container.jl
src/core/simulation.jl
src/core/simulation_results.jl
src/utils.jl
test/test_operations_constructor.jl
test/test_operations_solve.jl
test/test_simulation_execute.jl
test/test_simulation_results.jl

This PR adds more tests to the code, it won't fully restore coverage but its a step forward.

simulation and tests updates

---

Project.toml
src/core/hdf_simulation_store.jl
src/core/simulation.jl
src/utils.jl

This also updates the HDF5.jl version and fixes associated obsolete function calls.
The new HDF5 package fixes the performance issue when repeatedly calling open/read/close on a .h5 file.

Cleanup non-handling of 3-d arrays in sim store

---

src/core/operations_problem.jl
src/core/psi_container.jl

This PR add a function to make checks for the psi_container. More checks could be added afterwards.

add psi container closure

---

src/devices_models/devices/AC_branches.jl
src/devices_models/devices/DC_branches.jl
src/devices_models/devices/hydro_generation.jl
src/devices_models/devices/interfaces.jl
src/devices_models/devices/regulation_device.jl
src/devices_models/devices/renewable_generation.jl
src/devices_models/devices/storage.jl
src/devices_models/devices/thermal_generation.jl
src/services_models/agc.jl
src/services_models/reserves.jl

I tried to remove all the defaults but there are too many. I also worry we have some type unstable functions that return nothing or a value and might require addressing.

remove problematic defaults

---

src/core/feedforward.jl
src/core/update_initial_conditions.jl
src/devices_models/devices/common/add_parameters.jl
src/devices_models/devices/common/energy_balance_constraint.jl
src/devices_models/devices/common/timeseries_constraint.jl
src/devices_models/devices/hydro_generation.jl
src/services_models/reserves.jl
src/utils.jl

pj deprecation

---

src/PowerSimulations.jl
src/core/definitions.jl
src/core/simulation.jl
src/core/simulation_results.jl
test/test_simulation_results.jl

Reverts NREL-SIIP/PowerSimulations.jl#631. I meant to merge my PR with the PJ deprecation fix.

Revert "Serialize simulation status"

---

src/devices_models/device_constructors/branch_constructor.jl
src/devices_models/devices/DC_branches.jl
test/test_device_branch_constructors.jl
test/test_utils/operations_problem_templates.jl

@claytonpbarrows we need to follow a similar approach for the other branches. For now this will suffice to avoud the ambiguities problems.

fix hvdc implementation

---

src/core/operations_problem.jl
src/devices_models/devices/common/rating_constraints.jl
src/printing.jl

Minor patches to the current release

011 patch2

---

src/core/param_result_cache.jl

This resulted in a runtime exception if is_dirty was called when the
deque is empty.

Fix bug by checking for empty deque

---

src/devices_models/devices/thermal_generation.jl

This adds the services to the ramp requirements.

add services to ramp constraints

---

test/runtests.jl

This is temporary PR to make the CI pass and continue development. Related to #654

disable tests

---

src/core/simulation.jl

If `get_increment` is intended to calculate the number of periods in the interval, then I think this PR corrects the calculation

fixing increment calculation

---

src/devices_models/devices/thermal_generation.jl

Creating new time limits by rounding the start time limits from hours to time periods.

Bug fix in Multi-start start type constraint 

---

test/test_operations_problem.jl
test/test_utils/model_checks.jl

bug fix in PTDF LMPs calculation

---

src/core/optimization_container.jl
src/devices_models/devices/DC_branches.jl
src/devices_models/devices/hydro_generation.jl
src/devices_models/devices/interfaces.jl
src/devices_models/devices/regulation_device.jl
src/devices_models/devices/renewable_generation.jl
src/devices_models/devices/storage.jl
src/devices_models/devices/thermal_generation.jl
src/network_models/powermodels_interface.jl
src/services_models/reserves.jl
src/services_models/services_constructor.jl

remove unused declarations

---

.github/workflows/format-check.yml

See https://github.com/reviewdog/action-suggester for more information.

Update format workflow to autosuggest changes to PRs

---

src/core/device_models.jl
src/core/optimization_container.jl
src/core/service_models.jl
src/core/simulation.jl
src/devices_models/devices/common/cost_functions.jl
src/devices_models/devices/common/pm_translator.jl
src/printing.jl
src/services_models/reserves.jl
src/services_models/services_constructor.jl
test/test_operations_template.jl

refactors model to follow the same patterns as the keys

performance patch 6

---

src/core/aux_structs.jl
src/core/cache.jl
src/core/simulation_sequence.jl
src/printing.jl
test/runtests.jl
test/test_simulation_sequence.jl
test/test_utils/mock_operation_models.jl

Enables SimulationSequence with new syntax

performance branch 7

---

src/core/simulation.jl

check execution in initical condition

---

src/core/simulation_sequence.jl
src/devices_models/device_constructors/common/constructor_validations.jl
src/devices_models/devices/storage.jl
src/services_models/services_constructor.jl

Solves some issues of modeling storage and services.

Fix services and storage modeling bugs 

---

src/core/feedforward.jl
src/core/optimization_container.jl
src/services_models/reserves.jl
src/services_models/services_constructor.jl

This PR is a bit hacky but enables passing a range_ff to services to set the reserve levels between stages. This code needs to be redone for v015 anyway so this is a temporary patch 
cc. @kdayday

support range ff for services

---

src/core/definitions.jl
src/devices_models/devices/thermal_generation.jl
src/services_models/reserves.jl

Fixes some issues with reserves

reserve fixes 

---

test/test_simulation_sequence.jl

In preparation for https://github.com/JuliaLang/julia/pull/41885

Generalize exception type

---

src/utils.jl

This change allows a simulation results directory to be moved or renamed. #Closes #684

Record relative path to file

---

src/core/optimization_container.jl
src/core/variables.jl
src/devices_models/device_constructors/hydrogeneration_constructor.jl
src/devices_models/devices/common/add_to_expression.jl
src/devices_models/devices/common/range_constraint.jl
src/devices_models/devices/electric_loads.jl
src/devices_models/devices/hydro_generation.jl
src/devices_models/devices/storage.jl
src/devices_models/devices/thermal_generation.jl
src/network_models/network_constructor.jl
src/network_models/network_slack_variables.jl
src/network_models/powermodels_interface.jl
src/operation/model_cache.jl
src/services_models/agc.jl
test/test_model_decision.jl

-  updating ICkey methods
- Bug fixes  hydro
- Bug fixes  load
- Fixes the PTDFPowerModel (but one test is still failing obj values don't match)
- Changes to VariableKey code

Fixing multiple issue

---

src/core/optimization_container.jl
src/core/optimizer_stats.jl
src/devices_models/devices/hydro_generation.jl
src/devices_models/devices/thermal_generation.jl
src/feedforward/feedforward_constraints.jl
src/initial_conditions/update_initial_conditions.jl
src/simulation/initial_condition_update_simulation.jl
src/simulation/simulation.jl
src/simulation/simulation_state.jl
test/test_device_hydro_generation_constructors.jl
test/test_simulation_execute.jl

Some of the changes in this branch are not completely implemented

General code clean up and bug fixes

---

docs/src/index.md
docs/src/man/multistart_formulation.md
docs/src/man/storage_energy_target.md

I've just fixed a few typos in the documentation. 
Thank you very much for the development and maintenance of this package!

Fixed a few typos in the docs 

---

src/PowerSimulations.jl
src/core/constraints.jl
src/core/definitions.jl
src/core/optimization_container.jl
src/devices_models/devices/common/cost_functions.jl
src/devices_models/devices/thermal_generation.jl
src/initial_conditions/initialization.jl
src/operation/operation_model_interface.jl
src/operation/optimization_debugging.jl
test/test_utils/model_checks.jl

Some miscellaneous fixes I found while debugging the texas model.

misc fixes

---

src/PowerSimulations.jl
src/core/constraints.jl
src/devices_models/device_constructors/regulationdevice_constructor.jl
src/devices_models/devices/common/add_to_expression.jl
src/devices_models/devices/common/cost_functions.jl
src/devices_models/devices/regulation_device.jl
src/devices_models/devices/thermal_generation.jl
src/feedforward/feedforward_constraints.jl
src/services_models/agc.jl
src/services_models/services_constructor.jl
test/test_services_constructor.jl

The values in the tests changed because in the new implementation we don't have the hack that created the system balance during the device constraint building.

restore agc

---

src/core/optimization_container.jl
src/devices_models/device_constructors/hydrogeneration_constructor.jl
src/devices_models/devices/common/add_to_expression.jl
src/devices_models/devices/common/objective_functions.jl
src/devices_models/devices/common/rateofchange_constraints.jl
src/devices_models/devices/thermal_generation.jl
src/feedforward/feedforward_arguments.jl
src/feedforward/feedforward_constraints.jl
src/parameters/update_parameters.jl
test/Project.toml
test/test_device_thermal_generation_constructors.jl
test/test_simulation_build.jl

This PR addresses an issue with semicontinuous FF when there are ramp constraints.

ff ramps fix

---

src/devices_models/devices/common/rateofchange_constraints.jl
src/devices_models/devices/hydro_generation.jl
src/devices_models/devices/storage.jl
src/devices_models/devices/thermal_generation.jl

* This should address the pumped hydro auxiliary variable issue Jarred mentioned
* Bug fix on slack variable bounds used for storage energy target formulations
* Fixes #893

Minor bug fixes

---

src/operation/decision_model.jl
src/operation/decision_model_store.jl

allow double calls to solve for decision models

---

src/utils/generate_valid_formulations.jl

This is a work around while we update the PSY AbstractTypes. closes #907

not show dynamic branch in docs

---

src/devices_models/device_constructors/branch_constructor.jl
src/devices_models/devices/AC_branches.jl

Updates de code to use only branches in the PTDF

add changes to PTDF models construction

---

src/devices_models/devices/common/add_variable.jl
src/devices_models/devices/common/objective_functions.jl
src/devices_models/devices/interfaces.jl
src/devices_models/devices/thermal_generation.jl
test/test_device_thermal_generation_constructors.jl

Closes #948 and give more flexibility to handle OnVariables for different components such as Hybrids.

Thermal OnVariable updates

---

src/core/optimization_container.jl
src/devices_models/device_constructors/branch_constructor.jl
src/devices_models/device_constructors/constructor_validations.jl
src/devices_models/device_constructors/hydrogeneration_constructor.jl
src/devices_models/device_constructors/load_constructor.jl
src/devices_models/device_constructors/renewablegeneration_constructor.jl
src/devices_models/device_constructors/thermalgeneration_constructor.jl
src/devices_models/devices/common/add_constraint_dual.jl
src/devices_models/devices/hydro_generation.jl
src/network_models/pm_translator.jl
src/parameters/update_parameters.jl
src/utils/powersystems_utils.jl
test/test_model_decision.jl

This PR adds the possibility to define a filter function attribute in the device models. Needs some additional testing

add device filter

---

docs/Project.toml
docs/make.jl
docs/src/api/PowerSimulations.md
docs/src/code_base_developer_guide/developer.md
docs/src/formulation_library/Branch.md
docs/src/formulation_library/General.md
docs/src/formulation_library/HydroGen.md
docs/src/formulation_library/Load.md
docs/src/formulation_library/Network.md
docs/src/formulation_library/RenewableGen.md
docs/src/formulation_library/ThermalGen.md
docs/src/index.md
docs/src/modeler_guide/problem_templates.md
docs/src/modeler_guide/psi_structure.md
docs/src/modeler_guide/running_a_simulation.md
docs/src/quick_start_guide.md
docs/src/tutorials/decision_problem.md
docs/src/tutorials/pcm_simulation.md
src/operation/decision_model.jl
src/operation/emulation_model.jl
src/operation/problem_results.jl

adding initial tutorials and docs cleanup

migrate tutorials

---

src/devices_models/devices/thermal_generation.jl

Corrects a previous mistake. The PR will automatically update to main once the larger PR is merged.

add correction to lb

---

test/runtests.jl
test/test_simulation_results.jl

The PRs #1060 and #1062 were logically incompatible but didn’t have any git merge conflicts. This resolves the errors.

Fix merge errors with #1060 and #1062

---

src/core/definitions.jl
src/core/variables.jl
src/devices_models/device_constructors/branch_constructor.jl
src/devices_models/devices/AC_branches.jl
src/operation/model_numerical_analysis_utils.jl
src/operation/operation_model_interface.jl
test/test_device_branch_constructors.jl
test/test_network_constructors.jl
test/test_utils/operations_problem_templates.jl
test/test_utils/solver_definitions.jl

This PR adds the capability to have slacks on the line flows for ACBranches. It doesn't apply to HVDC yet.

branch flow slacks

---

src/core/optimizer_stats.jl
test/test_utils.jl

fix optimizer stats backwards compatibility

---

src/devices_models/devices/common/add_to_expression.jl

this is required to fix the HSS code

use service name in meta

---

src/network_models/network_constructor.jl

add slackdown to Reactive Balance

---

src/devices_models/device_constructors/branch_constructor.jl
src/devices_models/devices/common/add_to_expression.jl

Fix bugs branches and HVDC

---

src/core/event_model.jl
src/simulation/simulation_events.jl

First pass at checking event conditions. 
WIP: need cleaner/more robust reading of simulation state for `StateVariableValueCondition`

first pass; checking conditions

---

src/feedforward/feedforward_arguments.jl
src/services_models/services_constructor.jl
test/test_services_constructor.jl

Temporary error workaround while we rework TransmissionInterface formulations

update TransmissionInterface to fail with FFs

---

src/devices_models/devices/common/objective_function/market_bid.jl

Partially addresses https://github.com/NREL-Sienna/PowerSimulations.jl/issues/1260.

Fix test failures in PR 1182

---

.github/workflows/cross-package-test.yml

Adds PowerAnalytics.jl to the CrossPackageTest action alongside the existing HydroPowerSimulations and StorageSystemsSimulations.

Add `PowerAnalytics` to CI cross-package tests

---

src/network_models/power_flow_evaluation.jl
test/test_simulation_results.jl

See https://github.com/NREL-Sienna/PowerSimulations.jl/issues/1273. This adopts the fix proposed there, along with testing that component names in power flow results match the system and optimizer results.

Fix bug 1273

---

src/devices_models/devices/common/add_to_expression.jl
src/devices_models/devices/common/objective_function/market_bid.jl
src/utils/powersystems_utils.jl
test/test_device_load_constructors.jl

- Removed code duplication from market_bid.jl.
- Removed `get_variable(cost::MarketBidCost) = nothing`
- Changed `string()` to `nameof()`
- Removed `is_convex_decremental` and used newly created `is_concave` from IS. Depends on related PRs in [IS](https://github.com/NREL-Sienna/InfrastructureSystems.jl/pull/445) and [PowerSystems](https://github.com/NREL-Sienna/PowerSystems.jl/pull/1295)

Fix issues in https://github.com/NREL-Sienna/PowerSimulations.jl/issues/1260

---

docs/src/formulation_library/Branch.md
src/core/constraints.jl
src/core/definitions.jl
src/core/formulations.jl
src/core/variables.jl
src/devices_models/device_constructors/branch_constructor.jl
src/devices_models/devices/AC_branches.jl
src/devices_models/devices/TwoTerminalDC_branches.jl
src/devices_models/devices/common/add_to_expression.jl
src/network_models/pm_translator.jl
src/operation/operation_problem_templates.jl
src/utils/powersystems_utils.jl
test/test_device_branch_constructors.jl
test/test_device_lcc.jl
test/test_network_constructors.jl
test/test_utils/operations_problem_templates.jl

Add LCC physical model

---

src/devices_models/device_constructors/load_constructor.jl
src/devices_models/devices/electric_loads.jl
test/test_device_load_constructors.jl

add On Limit for LoadInterruption

---

src/network_models/power_flow_evaluation.jl
test/test_simulation_results.jl

Fixes #1320, see there for description.

Fix bug #1320 by adding unit conversions; test

---

src/core/initial_conditions.jl
src/core/optimization_container.jl
src/initial_conditions/add_initial_condition.jl
src/utils/jump_utils.jl

I tested this change with HydroPowerSimulations branch feat/3d-resultsv2.

Support 3d initial conditions
